/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author elisi
 */
public class jfprincipal extends javax.swing.JFrame {

        public static boolean cadastro, cadastro1;
        
    /**
     * Creates new form jfprincipal
     */
    public jfprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmcadastro = new javax.swing.JMenu();
        jmcandidato = new javax.swing.JMenuItem();
        jmeleitor = new javax.swing.JMenuItem();
        jmvotos = new javax.swing.JMenu();
        jmconsulta = new javax.swing.JMenuItem();
        jmlista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("elisioaal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jmcadastro.setText("Cadastro");

        jmcandidato.setText("Candidato");
        jmcandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcandidatoActionPerformed(evt);
            }
        });
        jmcadastro.add(jmcandidato);

        jmeleitor.setText("Eleitor");
        jmeleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeleitorActionPerformed(evt);
            }
        });
        jmcadastro.add(jmeleitor);

        jMenuBar1.add(jmcadastro);

        jmvotos.setText("Votos");
        jmvotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmvotosActionPerformed(evt);
            }
        });

        jmconsulta.setText("Consulta");
        jmconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmconsultaActionPerformed(evt);
            }
        });
        jmvotos.add(jmconsulta);

        jmlista.setText("Lista");
        jmlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlistaActionPerformed(evt);
            }
        });
        jmvotos.add(jmlista);

        jMenuBar1.add(jmvotos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpprincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        jfprincipal.cadastro = false;
    }//GEN-LAST:event_formWindowOpened

    private void jmcandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcandidatoActionPerformed
        
        if(cadastro == false){
        jifcandidato obj = new jifcandidato();
        jdpprincipal.add(obj);
        obj.setVisible(true);
        }//fim do if
    }//GEN-LAST:event_jmcandidatoActionPerformed

    private void jmeleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeleitorActionPerformed
        
        if(cadastro1 == false){
        jifeleitor obj = new jifeleitor();
        jdpprincipal.add(obj);
        obj.setVisible(true);
        }//fim do if
    }//GEN-LAST:event_jmeleitorActionPerformed

    private void jmconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmconsultaActionPerformed
        
        jifconsulta obj = new jifconsulta();
        jdpprincipal.add(obj);
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_jmconsultaActionPerformed

    private void jmvotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmvotosActionPerformed
        
        
        
    }//GEN-LAST:event_jmvotosActionPerformed

    private void jmlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlistaActionPerformed
        
        if(cadastro == false){
        jiflistagem obj = new jiflistagem();
        jdpprincipal.add(obj);
        obj.setVisible(true);
        }//fim do if
    }//GEN-LAST:event_jmlistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpprincipal;
    private javax.swing.JMenu jmcadastro;
    private javax.swing.JMenuItem jmcandidato;
    private javax.swing.JMenuItem jmconsulta;
    private javax.swing.JMenuItem jmeleitor;
    private javax.swing.JMenuItem jmlista;
    private javax.swing.JMenu jmvotos;
    // End of variables declaration//GEN-END:variables
}
